name: Flask Docker AWS 

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      #- name: Set working directory
      #  working-directory: ./docker_aws_cicd
      #  run: cd ./docker_aws_cicd

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Running unit testcases
        run: pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t  sivamaniv8/flask_docker_aws_cicd .

      - name: Publish docker image to docker hub
        run: docker push sivamaniv8/flask_docker_aws_cicd:latest

  deploy:
    #if: "!contains(github.event.commits[0].message, '[skip ci]')"
    if: ${{ !contains(github.event.head_commit.message, '#ecs') }}
    needs: build
    runs-on: [aws_ec2]
    steps:
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Pull image from docker hub
        run: docker pull sivamaniv8/flask_docker_aws_cicd:latest

      - name: Delete existing container
        run: docker rm -f flask_docker_aws_cicd_container

      - name: Run docker container
        run: docker run -d -p 7000:7000 --name flask_docker_aws_cicd_container sivamaniv8/flask_docker_aws_cicd
    
